name: Cypress

on: pull_request

jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: cypress-io/github-action@v2
        with:
          command: npm run test:ci
          config: baseUrl=http://localhost:8000
      - uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots
