name: Firebase

on:
  push:
    branches:
    - master
jobs:
  firebase-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-node@master
      with:
        node-version: 10.x
    - uses: DamianReeves/write-file-action@v1.0
      with:
        path: .env.production
        contents: |
          MATOMO_URL=${{ secrets.MATOMO_URL }}
          MATOMO_SITE_ID=${{ secrets.MATOMO_SITE_ID }}
          FRESHCHAT_TOKEN=${{ secrets.FRESHCHAT_TOKEN }}
          FRESHCHAT_HOST=${{ secrets.FRESHCHAT_HOST }}
          FUNCTIONS_HOST=${{ secrets.FUNCTIONS_HOST }}
        write-mode: overwrite
    - run: npm install
    - run: npm run clean
    - run: npm run build
      env:
        NOTION_COLLECTION_ID: ${{ secrets.NOTION_COLLECTION_ID }}
        NOTION_COLLECTION_VIEW: ${{ secrets.NOTION_COLLECTION_VIEW }}
    - uses: w9jds/firebase-action@master
      with:
        args: deploy --only hosting:minimum-viable-marketing --project ${{ secrets.FIREBASE_DOMAIN }}
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
